name: glosh
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  flutter_native_splash: ^2.0.5
  get: ^4.6.1
  flashy_tab_bar2: ^0.0.4
  flutter_staggered_animations: ^1.0.0
  lottie: ^1.2.2
  shimmer: ^2.0.0
  loading_indicator: ^3.0.2
  iconsax: ^0.0.8
  carousel_slider: ^4.0.0
  dotted_border: ^2.0.0+2
  cool_alert: ^1.1.0
  firebase_core: ^1.13.0
  firebase_storage: ^10.2.8
  fluttertoast: ^8.0.9
  dio: ^4.0.4
  dartz: ^0.10.1
  http: ^0.13.4
  intl: ^0.17.0
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splashlogo.png
  color_dark: "#313131"
  image_dark: assets/images/splashlogo.png
  android: true
  ios: false
  web: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_logo.png"